#pragma once
#define DIRECTORY_SIZE 128
#define TABLE_SIZE 128
#define VA_SIZE 24
#define PAGE_BITS 14
#define OFFSET_BITS 10
#define NO_OF_PAGES (1<<PAGE_BITS)
#define DESCRIPTOR_SIZE 8
#define PAGEMAP_CHUNK 100
#define NULL_FRAME 0xffffffff
#define TABLE_NUMBER_BITS 7
#define PAGE_NUMBER_BITS 7
#define MAX_VA ((1<<VA_SIZE)-1)
#define OFFSET_MASK ((1<<OFFSET_BITS)-1)
#define PAGE_MASK (((1<<PAGE_NUMBER_BITS)-1)<<OFFSET_BITS)
#define TABLE_MASK (((1<<TABLE_NUMBER_BITS)-1)<<(OFFSET_BITS+PAGE_NUMBER_BITS))

#define MIN_WORKINGSET 5
#define MAX_WORKINGSET ((1<<PAGE_BITS)-1)
#define INITIAL_WORKINGSET 6
#define TOLERABLE_FAULTRATE (0.05f)
#define VERY_SMALL_FAULTRATE (0.005f)
#define WORKING_SET_INCREMENT (1.6f) 
#define WORKING_SET_DECREMENT (1.2f)
#define SWAPPINES (0.8f)
